# Loading libraries

In [1]:
import pandas as pd
import numpy as np
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /home/vscode/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/vscode/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

# Load data

In [2]:
# Load data
corpus = pd.read_excel('cleaned_corpus.xlsx')

# Convert date_published as datetime data type
corpus['date_published'] = pd.to_datetime(
  corpus['date_published']
)

## Inspecting the data

In [3]:
corpus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851 entries, 0 to 850
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   title            851 non-null    object
 1   link             851 non-null    object
 2   date_published   851 non-null    datetime64[ns]
 3   text             850 non-null    object
 4   source           851 non-null    object
 5   like_count       826 non-null    float64
 6   reply_parent_id  98 non-null     object
 7   cleaned_text     838 non-null    object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 53.3+ KB

In [4]:
display(
  corpus.head()
)
display(
  corpus.tail()
)

,title,link,date_published,text,source,like_count,reply_parent_id,cleaned_text
0,Hindi Ito Marites: The Hague and Filipinos' pu...,https://www.rappler.com/newsbreak/podcasts-vid...,2025-08-15 16:00:29,"When local courts offer no refuge, or when fac...",rappler,NaN,NaN,local court offer refuge face formid foreign a...
1,FACT CHECK: No Guinness record of Duterte as ‘...,https://www.rappler.com/newsbreak/fact-check/n...,2025-08-12 10:00:00,Claim: Former president Rodrigo Duterte holds ...,rappler,NaN,NaN,claim former presid rodrigo dutert hold guin w...
2,WATCH: Tuloy ba ang pre-trial hearing ni Duter...,https://www.rappler.com/philippines/video-will...,2025-08-11 19:00:00,"MANILA, Philippines – May bagong hiling ang de...",rappler,NaN,NaN,manila philippin may bagong hile ang defens te...
3,Duterte team wants ICC Prosecutor Khan disqual...,https://www.rappler.com/video/daily-wrap/augus...,2025-08-08 22:07:53,Here are today’s headlines – the latest news i...,rappler,NaN,NaN,today headlin latest news philippin around wor...
4,Duterte team wants Prosecutor Khan disqualifie...,https://www.rappler.com/philippines/duterte-de...,2025-08-08 07:00:00,"MANILA, Philippines – Prosecutor Karim Khan, o...",rappler,NaN,NaN,manila philippin prosecutor karim khan leav in...

,title,link,date_published,text,source,like_count,reply_parent_id,cleaned_text
846,Ul*l dignified. Pinapakyuhan nga si Bong Daza ...,https://www.youtube.com/watch?v=yfoq-0gGTLM&lc...,2024-08-27 19:24:46,Ul*l dignified. Pinapakyuhan nga si Bong Daza ...,youtube,0.0,UgwBBzeGtqWna6y4KUJ4AaABAg,ul l dignified pinapakyuhan nga si bong daza s...
847,"That vp is rude, entitled and arrogant like he...",https://www.youtube.com/watch?v=yfoq-0gGTLM&lc...,2024-08-27 21:13:32,"That vp is rude, entitled and arrogant like he...",youtube,3.0,UgwBBzeGtqWna6y4KUJ4AaABAg,vp rude entitl arrog like father they r use sp...
848,What country is this? Very interesting.,https://www.youtube.com/watch?v=yfoq-0gGTLM&lc...,2024-08-27 22:16:52,What country is this? Very interesting.,youtube,0.0,UgwBBzeGtqWna6y4KUJ4AaABAg,countri this veri interesting
849,@@cvoutdoors9859palamunin,https://www.youtube.com/watch?v=yfoq-0gGTLM&lc...,2024-08-27 23:14:26,@@cvoutdoors9859palamunin,youtube,0.0,UgwBBzeGtqWna6y4KUJ4AaABAg,cvoutdoors palamunin
850,That’s true,https://www.youtube.com/watch?v=yfoq-0gGTLM&lc...,2024-08-28 02:00:32,That’s true,youtube,0.0,UgwBBzeGtqWna6y4KUJ4AaABAg,that true

# Topic Modeling

In [5]:
# !pip install pyLDAvis

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import pyLDAvis

## Document-Term Matrix

In [9]:
vectorizer = CountVectorizer(
  max_df=0.95,  # terms that appears 95% within the corpus
  min_df=2,  # terms that appear at 2x within the corpus
  stop_words='english'  # ignore english stopwords
)
doc_term_matrix = vectorizer.fit_transform(
  corpus['cleaned_text']
)

doc_term_matrix.toarray().shape
# (851, 2065) --> 851 documents and 2065 unique words

(851, 2065)

In [10]:
pd.DataFrame(
  doc_term_matrix.toarray()
)

,0,1,2,3,4,5,6,7,8,9,...,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
846,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
847,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
848,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
849,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
850,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## LDA

In [11]:
LDA = LatentDirichletAllocation(
  n_components=5,  # no. of topics
  random_state=42  # random seed for replicability
)
LDA.fit(doc_term_matrix)

LatentDirichletAllocation(n_components=5, random_state=42)

In [12]:
len(LDA.components_)

5

## Topic-Term Matrix

In [13]:
topic_term_matrix = LDA.components_
pd.DataFrame(topic_term_matrix)

,0,1,2,3,4,5,6,7,8,9,...,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064
0,0.200024,0.200001,0.200014,0.200176,1.197586,0.209956,1.642114,0.200015,0.200001,0.215278,...,0.200009,0.201488,0.200000,0.201766,0.200003,1.198690,0.200004,0.200996,1.187797,0.200001
1,0.202987,0.200023,0.202604,0.200089,0.200882,0.205273,0.202932,1.196670,0.200023,1.255893,...,0.201294,0.229268,0.200000,0.202160,0.207738,0.200003,0.201262,0.423505,3.202011,0.200000
2,2.064584,0.200162,0.200003,6.199115,0.201733,0.200003,0.200000,0.202585,0.200568,0.200227,...,3.198614,6.169229,0.200000,0.200001,0.200001,0.200106,9.444568,53.969274,0.209043,0.200000
3,0.202350,0.200000,3.196586,0.200007,0.201574,0.200852,0.200001,1.387988,0.200000,2.621831,...,0.200006,0.200011,0.200000,4.993893,4.201712,0.201061,0.200439,0.200273,0.200009,2.844236
4,3.330054,3.199815,0.200792,0.200612,1.198224,6.183916,2.754953,4.012741,3.199408,9.706772,...,0.200077,0.200003,2.199999,1.402181,1.190545,3.200140,1.953728,0.205951,0.201140,4.555763

In [14]:
topic1 = topic_term_matrix[0]
topic1

# sort the scores from lowest to highest
# will return all terms
topic1.argsort()

# select top 10 terms within topic1
topic1_term_index = topic1.argsort()[-10:]

# convert back to words/terms
[vectorizer.get_feature_names_out()[index] for index in topic1_term_index]

['presid',
 'mr',
 'intern',
 'whi',
 'judg',
 'god',
 'speak',
 'stand',
 'english',
 'dutert']

In [15]:
for topic_number, topic in enumerate(LDA.components_):
  print(f'The top 10 words for topic #{topic_number}')
  print(
    [
      vectorizer.get_feature_names_out()[term_index] for term_index in topic.argsort()[-5:]
    ]
  )
  print("\n")

The top 10 words for topic #0
['god', 'speak', 'stand', 'english', 'dutert']


The top 10 words for topic #1
['hi', 'mo', 'nya', 'peopl', 'drug']


The top 10 words for topic #2
['mga', 'ng', 'na', 'ang', 'sa']


The top 10 words for topic #3
['hi', 'said', 'dutert', 'thi', 'presid']


The top 10 words for topic #4
['duterte', 'wa', 'philippin', 'hi', 'dutert']

## Document-Topic Matrix

In [16]:
doc_topic_matrix = LDA.transform(doc_term_matrix)
pd.DataFrame(doc_topic_matrix)

            0         1         2         3         4
0    0.003045  0.003053  0.003040  0.003094  0.987767
1    0.000984  0.000984  0.001021  0.000995  0.996015
2    0.001943  0.001930  0.703924  0.001940  0.290262
3    0.045648  0.002764  0.002744  0.002806  0.946038
4    0.000577  0.000577  0.000574  0.000580  0.997692
..        ...       ...       ...       ...       ...
846  0.011112  0.011148  0.955473  0.011154  0.011113
847  0.010724  0.010867  0.010527  0.419848  0.548033
848  0.066755  0.731034  0.066700  0.068251  0.067259
849  0.200000  0.200000  0.200000  0.200000  0.200000
850  0.596473  0.100007  0.100003  0.103515  0.100002

[851 rows x 5 columns]

In [18]:
corpus['Topic'] = doc_topic_matrix.argmax(axis=1)
display(
  corpus[['cleaned_text', 'source', 'Topic']]
)
corpus[['cleaned_text', 'source', 'Topic']].to_excel('topic_documents.xlsx')

                                          cleaned_text   source  Topic
0    local court offer refuge face formid foreign a...  rappler      4
1    claim former presid rodrigo dutert hold guin w...  rappler      4
2    manila philippin may bagong hile ang defens te...  rappler      2
3    today headlin latest news philippin around wor...  rappler      4
4    manila philippin prosecutor karim khan leav in...  rappler      4
..                                                 ...      ...    ...
846  ul l dignified pinapakyuhan nga si bong daza s...  youtube      2
847  vp rude entitl arrog like father they r use sp...  youtube      4
848                      countri this veri interesting  youtube      1
849                               cvoutdoors palamunin  youtube      0
850                                          that true  youtube      0

[851 rows x 3 columns]

In [24]:
display(
  corpus.query("Topic == 2 and source == 'rappler'")['text']
)

display(
  corpus.query("Topic == 1 and source == 'youtube'")['text']
)

2     MANILA, Philippines – May bagong hiling ang de...
13    MANILA, Philippines – Naka-schedule humarap si...
Name: text, dtype: object

34     THE PHILLIPPINNES Govermennt Is Sourounded be ...
50     At the very least, the ICC should have represe...
54     Mercy boucoup , , our beloved Country & France...
85     The USA plays the major role in this kidnappin...
91     Well, serves him right, hypocrite to ask fo du...
                             ...
806            In your thoughts and in your only dreams.
815    Why would Indonesia arrest her if she didn’t c...
818    Only this type of human race can go anywhere i...
845                                         Very singhot
848              What country is this? Very interesting.
Name: text, Length: 114, dtype: object

## Visualize using PyLDAViz

In [26]:
vocab = vectorizer.get_feature_names_out()
doc_lengths = [
  len(doc) for doc in corpus['cleaned_text']
]
term_freq = doc_term_matrix.sum(axis=0)
term_freqs = np.array(term_freq).flatten()
vis_data = pyLDAvis.prepare(topic_term_matrix, doc_topic_matrix, doc_lengths, vocab, term_freqs)

pyLDAvis.display(vis_data)