---
**Topic Modelling** for Reddit Dataset

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import nltk
from nltk.corpus import stopwords
import re

nltk.download('stopwords')
stop_words = stopwords.words('english')

reddit_clean = pd.read_csv("../data/Reddit/reddit_clean.csv")

# reddit_clean['text'] = reddit_clean['post_full'].fillna('') + " " + reddit_clean['comment'].fillna('')
reddit_clean.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Uwie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,post_title,post_url,comment,post_body,created_utc,post_full
0,"Sen. Marcoleta to hold Blue Ribbon Committee, ...",https://reddit.com/r/Philippines/comments/1ltr...,NaN,"Oh God, Marcos Camp is in danger of opening a ...",2025-07-07 11:40:47,"sen. marcoleta to hold blue ribbon committee, ..."
1,"Sen. Marcoleta to hold Blue Ribbon Committee, ...",https://reddit.com/r/Philippines/comments/1ltr...,"buti naman si kiko papalit sa agriculture, dam...",NaN,2025-07-07 12:38:47,"sen. marcoleta to hold blue ribbon committee, ..."
2,"Sen. Marcoleta to hold Blue Ribbon Committee, ...",https://reddit.com/r/Philippines/comments/1ltr...,may sumpa rin ang blue ribbon. tolentino - tal...,NaN,2025-07-07 12:21:50,"sen. marcoleta to hold blue ribbon committee, ..."
3,"Sen. Marcoleta to hold Blue Ribbon Committee, ...",https://reddit.com/r/Philippines/comments/1ltr...,bobo naman bakit sa kanya blue ribbon committee,NaN,2025-07-07 11:51:43,"sen. marcoleta to hold blue ribbon committee, ..."
4,"Sen. Marcoleta to hold Blue Ribbon Committee, ...",https://reddit.com/r/Philippines/comments/1ltr...,blue ribbon committee is a curse seat lol yeah...,NaN,2025-07-07 12:46:06,"sen. marcoleta to hold blue ribbon committee, ..."

In [4]:
# Stopwrods

import nltk
from nltk.corpus import stopwords

nltk.download("stopwords")
english_stop = stopwords.words("english")

filipino_stopwords = [
    "sa","ang","ng","mga","si","ni","kay","kina",
    "ito","iyan","iyon","doon","diyan","dito",
    "ko","mo","nya","niya","natin","namin","nyo","ninyo",
    "sila","kami","tayo","kayo",
    "ay","may","wala","meron","naman","rin","din",
    "pa","ba","po","ho","eh","yung","yup","nope",
    "kung","kapag","pero","kasi","para","habang","bago",
    "nga","lang","daw","raw","yata","pala","talaga",
    "siguro","naka","ni","siya",
    
    # noise words
    "haha","hahaha","hehe","lol","omg","hmmmm","hmmmmmm",
    "tsk","hay","amp","grabe",
    
    # more noise as the code is ran
    "lalala", "brgy", "sen", "ph", "phl", "gov",
    "committee", "chairmanships"
]

combined_stopwords = list(set(english_stop + filipino_stopwords))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Uwie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:
texts = reddit_clean["post_full"].dropna().tolist()

# Added after first run through.
extra_stop = [
    "sa","ang","ng","mga","na","pa","ba","ay","ni","kay","ito",
    "ko","mo","si","rin","din","yan","nya","hmmmmmm","haha","hehe","ho"
]

tfidf_vectorizer = TfidfVectorizer(
    max_df=0.85,
    min_df=5,
    stop_words=list(set(extra_stop).union(combined_stopwords))
)

tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

# Fit LDA model
n_topics = 5  # adjust after testing
lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    learning_method='batch'
)
lda_model.fit(tfidf_matrix)

# Display topics
def display_topics(model, feature_names, num_top_words=10):
    for idx, topic in enumerate(model.components_):
        print(f"\nTopic {idx + 1}:")
        print(" | ".join([feature_names[i] for i in topic.argsort()[:-num_top_words - 1:-1]]))

feature_names = tfidf_vectorizer.get_feature_names_out()
display_topics(lda_model, feature_names)

Topic 1:
agriculture | fb | total | professionals | licensed | lawyers | excluding | account | contreras | antonio

Topic 2:
mas | clearance | philippines | career | path | worth | live | innovation | imagine | agriculture

Topic 3:
degree | useful | college | feed | fish | farmers | agriculture | rice | philippines | growing

Topic 4:
profession | undervalued | philippines | industry | appreciated | field | least | name | sadly | one

Topic 5:
announces | senate | national | sad | else | bookstore | enter | feels | country | agricultural

In [8]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english') + combined_stopwords

from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(
    max_df=0.85,
    min_df=5,
    stop_words=stop_words
)
count_matrix = count_vectorizer.fit_transform(reddit_clean["post_full"].dropna())
lda_model.fit(count_matrix)
feature_names = count_vectorizer.get_feature_names_out()
display_topics(lda_model, feature_names)

Topic 1:
philippines | agriculture | research | secretary | total | number | licensed | professionals | lawyers | fb

Topic 2:
na | agriculture | duterte | mas | fish | clearance | feed | man | ring | agricultural

Topic 3:
agriculture | agricultural | national | else | sad | enter | feels | bookstore | country | philippines

Topic 4:
philippines | profession | undervalued | agriculture | least | one | field | live | list | worth

Topic 5:
agriculture | rice | farmers | president | senate | marcos | problem | guilt | tarrification | philippines

---
**Topic Modelling** for Rappler dataset

In [11]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
import nltk
from nltk.corpus import stopwords
import re

nltk.download('stopwords')
stop_words = stopwords.words('english')

rappler_clean = pd.read_csv("../data/News/rappler_clean.csv")

# reddit_clean['text'] = reddit_clean['post_full'].fillna('') + " " + reddit_clean['comment'].fillna('')
rappler_clean.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Uwie\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,title,link,date_published,text,cleaned_text
0,Arms to farms: Maguindanao del Sur’s agricultu...,https://www.rappler.com/philippines/mindanao/m...,2025-10-21T12:18:03+08:00,"COTABATO CITY, Philippines —Maguindanao del Su...","cotabato city, philippines —maguindanao del su..."
1,Chinese smugglers ‘operate freely’ with help o...,https://www.rappler.com/business/chinese-smugg...,2025-10-20T18:41:06+08:00,"MANILA, Philippines – Chinese smugglers, Phili...","manila, philippines – chinese smugglers, phili..."
2,Bounty Fresh aims to strengthen operations ami...,https://www.rappler.com/business/bounty-fresh-...,2025-10-19T15:37:55+08:00,"MANILA, Philippines – Bounty Fresh is focusing...","manila, philippines – bounty fresh is focusing..."
3,Century Pacific buys another coconut facility....,https://www.rappler.com/business/century-pacif...,2025-10-17T01:07:37+08:00,"MANILA, Philippines – The Po family’s agribusi...","manila, philippines – the po family’s agribusi..."
4,[Ask the Tax Whiz] How do Filipinos benefit fr...,https://www.rappler.com/business/ask-the-tax-w...,2025-10-10T15:00:00+08:00,The two-tiered specific tax on Sweetened Bever...,the two-tiered specific tax on sweetened bever...

In [12]:
rtexts = rappler_clean["cleaned_text"].dropna().tolist()

# Added after first run through.
extra_stop = [
    "sa","ang","ng","mga","na","pa","ba","ay","ni","kay","ito",
    "ko","mo","si","rin","din","yan","nya","hmmmmmm","haha","hehe","ho"
]

tfidf_vectorizer = TfidfVectorizer(
    max_df=0.85,
    min_df=5,
    stop_words=list(set(extra_stop).union(combined_stopwords))
)

tfidf_matrix = tfidf_vectorizer.fit_transform(rtexts)

# Fit LDA model
n_topics = 5  # adjust after testing
lda_model = LatentDirichletAllocation(
    n_components=n_topics,
    random_state=42,
    learning_method='batch'
)
lda_model.fit(tfidf_matrix)

# Display topics
def display_topics(model, feature_names, num_top_words=10):
    for idx, topic in enumerate(model.components_):
        print(f"\nTopic {idx + 1}:")
        print(" | ".join([feature_names[i] for i in topic.argsort()[:-num_top_words - 1:-1]]))

feature_names = tfidf_vectorizer.get_feature_names_out()
display_topics(lda_model, feature_names)

Topic 1:
rice | da | prices | farmers | nfa | agriculture | food | laurel | kilo | marcos

Topic 2:
greater | technical | enhance | 2017 | business | chicken | founded | intended | 100 | strict

Topic 3:
greater | technical | enhance | 2017 | business | chicken | founded | intended | 100 | strict

Topic 4:
farm | soil | farming | company | asf | rural | fresh | communities | social | plants

Topic 5:
greater | technical | enhance | 2017 | business | chicken | founded | intended | 100 | strict

In [ ]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english') + combined_stopwords

from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer(
    max_df=0.85,
    min_df=5,
    stop_words=stop_words
)
count_matrix = count_vectorizer.fit_transform(rappler_clean["cleaned_text"].dropna())
lda_model.fit(count_matrix)
feature_names = count_vectorizer.get_feature_names_out()
display_topics(lda_model, feature_names)